version: "3.9"

services:
  db:
    image: postgres:16
    container_name: pkregistry_db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: public_key_registry
      TZ: Asia/Tokyo            # ← まとめてOK
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  public-key-registry:
    build: .
    container_name: public-key-registry
    ports:
      - "60000:60000"
    depends_on:
      - db
    environment:
      TZ: Asia/Tokyo
    restart: unless-stopped

volumes:
  pg_data:
